version: '2'
services:
  rethinkdb:
    image: rethinkdb
    ports:
      - '28015:28015' # Client Driver connection
      - '29015:29015' # Intracluster connections
      - '8080:8080' # Administrative HTTP connections
  redis:
    image: redis
    ports:
      - '6379:6379'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - '3000:3000'
    links:
      - rethinkdb
      - redis
#    env_file:
#      - .env.example
    environment:
      - RETHINKDB_HOST=rethinkdb
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "test"]
    volumes:
      - '.:/usr/src/app'
    links:
      - rethinkdb
#    env_file:
#      - .env.example
    environment:
      - RETHINKDB_HOST=rethinkdb
      - NODE_ENV=test
